### ISSUE TITLE
Use SWAM event chatLineAdded

### ISSUE THREAD

**Issue by Detect** [woot-airmash/speak-chat#5]
Can consider using [SWAM's chatLineAdded event](https://molesmalo.github.io/StarWarsMod4AirMash/Extensions-part1#events), which was added in today's [release](https://github.com/Molesmalo/StarWarsMod4AirMash/blob/master/changelog.md#mar-27-2018).

https://github.com/woot-airmash/speak-chat/blob/f948b9274ccaff0bbad0618dd85c9c33fdfa02b0/speak-chat.js#L139

edit: added changelog link

**Comment by woot-airmash** [comment]
Thanks that's a good idea. I spent a bit looking at the SWAM events and totally missed it :man_facepalming:

**Comment by woot-airmash** [comment]
Oh wait, if it was in today's release that makes more sense.

**Comment by woot-airmash** [comment]
Just changed over to the new SWAM event. Thanks for mentioning it, the mutation observer was a bit of a hack.
