### ISSUE TITLE
Respect sound setting of airmash

### ISSUE THREAD

**Issue by Detect** [woot-airmash/speak-chat#8]
There is an option to enable/disable sound in airmash (keybind g). Should this extension respect that sound setting?

**Comment by woot-airmash** [comment]
That's a good idea. Do you know if there's a sound setting from the game exposed anywhere?

I made a first try using a mutation observer.

**Comment by Detect** [comment]
`config.settings.sound`

**Comment by woot-airmash** [comment]
OK, I added that as the startup value but kept the mutation observer to handle any changes. Thanks for the feedback!

**Comment by Detect** [comment]
`config.settings.sound` does change based on current sound settings, so it's possible to use that in a conditional before TTS speaks as well.

**Comment by woot-airmash** [comment]
That's a way better solution :smile:. Just switched to that and erased the mutation observer part.
